language: node_js
node_js:
  - '10'
cache:
  directories:
    - 'node_modules'
services:
  - postgresql
addons:
  - postgresql: '9.6'
env:
  global:
    - PGPORT=5432
before_script:
  - psql -c 'CREATE DATABASE teamwork_api;' -U postgres
  - psql -c "CREATE USER api_user WITH PASSWORD 'password';" -U postgres
  - psql -c "ALTER ROLE api_user SUPERUSER;" -U postgres
  - psql -f "db/schema.sql" teamwork_api
after_success: npm run coverage
notifications:
  email:
    recipients:
      - sinkopus2000@gmail.com
<<<<<<< HEAD
=======

>>>>>>> 5e9636d71b09666b57f9c401f8eeb94d3b01b286
